version: '3.9'

services:
  users_postgres_db:
    image: postgres:17.4
    container_name: users_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - users_postgres_db_data:/var/lib/postgresql/data
    networks:
      - private-network

  keycloak_postgres_db:
    image: postgres:17.4
    container_name: keycloak_postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - keycloak_postgres_db_data:/var/lib/postgresql/data
    networks:
      - private-network

  subscriptions_postgres_db:
    image: postgres:17.4
    container_name: subscriptions_postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: subscriptions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - subscriptions_postgres_db_data:/var/lib/postgresql/data
    networks:
      - private-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgres_db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_postgres_db
    networks:
      - private-network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - private-network

  media_mongodb:
    image: mongo
    container_name: media_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: metadata
    ports:
      - '27017:27017'
    volumes:
      - media_mongo_data:/data/db
    networks:
      - private-network

  content_mongodb:
    image: mongo
    container_name: content_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: content
    ports:
      - '27018:27017'
    volumes:
      - content_mongo_data:/data/db
    networks:
      - private-network

  posts_mongodb:
    image: mongo
    container_name: posts_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: posts
    ports:
      - '27019:27017'
    volumes:
      - posts_mongo_data:/data/db
    networks:
      - private-network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - sonarqube_postgres_db
    ports:
      - "9002:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_postgres_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - sonar-network

  sonarqube_postgres_db:
    image: postgres:17.4
    container_name: sonarqube_postgres_db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube_postgresql:/var/lib/postgresql/data
    networks:
      - sonar-network

  content_service:
    build: ./content-service
    depends_on:
      - keycloak
      - config_service
      - discovery_service
      - content_mongodb
    networks:
      - private-network

  media_service:
    build: ./media-service
    depends_on:
      - keycloak
      - config_service
      - discovery_service
      - media_mongodb
      - minio
    networks:
      - private-network

  posts_service:
    build: ./posts-service
    depends_on:
      - keycloak
      - config_service
      - discovery_service
      - posts_mongodb
    networks:
      - private-network

  statistics_service:
    build: ./statistics-service
    depends_on:
      - keycloak
      - config_service
      - discovery_service
    networks:
      - private-network

  bff_service:
    build: ./bff-service
    ports:
      - "8081:8080"
    depends_on:
      - keycloak
    networks:
      - private-network

  config_service:
    build: ./config-service
    networks:
      - private-network

  discovery_service:
    build: ./discovery-service
    networks:
      - private-network

  subscriptions_service:
    build: ./subscriptions-service
    environment:
      CONFIG_SERVICE_URL: http://config_service:8888
    depends_on:
      - keycloak
      - config_service
      - discovery_service
      - subscriptions_postgres_db
    networks:
      - private-network

  users_service:
    build: ./users-service
    environment:
      CONFIG_SERVICE_URL: http://config_service:8888
    depends_on:
      - keycloak
      - config_service
      - discovery_service
      - users_postgres_db
    networks:
      - private-network

volumes:
  users_postgres_db_data: {}
  keycloak_postgres_db_data: {}
  subscriptions_postgres_db_data: {}
  minio_data: {}
  media_mongo_data: {}
  content_mongo_data: {}
  posts_mongo_data: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_postgresql: {}

networks:
  private-network:
  sonar-network: