server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ReShare
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 'http://localhost:3000'
            allowed-methods:
              - GET
              - POST
              - PUT
            allowed-headers: '*'
      default-filters:
        - TokenRelay
      routes:
        - id: users-route
          uri: ${USERS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1
        - id: subscribers-route
          uri: ${SUBSCRIBERS_ROUTE_URI:http://localhost:8083}
          predicates:
            - Path=/subscriptions/**
          filters:
            - PrefixPath=/api/v1
        - id: media-route
          uri: ${MEDIA_ROUTE_URI:http://localhost:8084}
          predicates:
            - Path=/media/**
          filters:
            - PrefixPath=/api/v1
        - id: content-route
          uri: ${CONTENT_ROUTE_URI:http://localhost:8085}
          predicates:
            - Path=/content/**
          filters:
            - PrefixPath=/api/v1
        - id: posts-route
          uri: ${POSTS_ROUTE_URI:http://localhost:8086}
          predicates:
            - Path=/posts/**
          filters:
            - PrefixPath=/api/v1
        - id: statistics-route
          uri: ${STATISTICS_ROUTE_URI:http://localhost:8087}
          predicates:
            - Path=/statistics/**
          filters:
            - PrefixPath=/api/v1
keycloak:
  client-id: reshare-client
