server:
  port: 8088

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ReShare
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://root:root@localhost:27020/payments?authSource=admin}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

keycloak:
  client-id: reshare-client

frontend:
  url: http://localhost:3000

stripe:
  secret-api-key: ${STRIPE_SECRET_API_KEY}
  public-api-key: ${STRIPE_PUBLIC_API_KEY}