server:
  port: 8086

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ReShare
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://root:root@localhost:27019/posts?authSource=admin}
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

keycloak:
  client-id: reshare-client
